site_name: Citrix Virtual Channel SDK for Citrix Workspace app for Windows
site_description: Reference for the Citrix Virtual Channel SDK for Citrix Workspace app for Windows
site_title: Developer Docs

# Copyright
copyright: 'Copyright &copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: https://citrix.com/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

# Customization
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - extra

# Page tree
nav:
- Introduction: index.md
- System Requirements: system-requirements.md
- Build Process: build-process.md
- Using the Virtual Channel SDK: using-the-sdk.md
- Using Example Programs: using-example-programs.md
- Programming Guide: programming-guide.md
- Programming Reference: programming-reference.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/
