site_name: Citrix Virtual Channel SDK for Citrix Workspace app for Windows
site_description: Reference for the Citrix Virtual Channel SDK for Citrix Workspace app for Windows
site_title: Developer Docs
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/workspace-windows-vcsdk/issues/new
assignees_uri:
  - shrukris
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs: false
  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'
# Page tree
nav:
- Introduction: index.md
- System Requirements: system-requirements.md
- Build Process: build-process.md
- Using the Virtual Channel SDK: using-the-sdk.md
- Using Example Programs: using-example-programs.md
- Programming Guide: programming-guide.md
- Programming Reference: programming-reference.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/
